### ISSUE TITLE
ENV vars - All are optional

### ISSUE THREAD

**Issue by app-generator** [app-generator/sample-fastapi-stripe#4]
Hello @barreraalexander 

All env variables are optional with defaults:

- Debug = True
- SECRET_KEY = random 16 chars
- Stripe secrets = None (Null)
- SERVER_HOST - `localhost:8000` (default uvicorn PORT)

Also, when the stripe secrets are not provided the UI shows the product but informs the user using an alert. 

> Flask version has all these evolutions 

![image](https://user-images.githubusercontent.com/51070104/196877128-5e839c81-7a28-43cc-adf0-126cc91cfcb0.png)

**Comment by barreraalexander** [comment]
All env variables are now optional. Defaults are provided in config.py.

**Comment by app-generator** [comment]
Hello @barreraalexander 

In the latest version, the vars are optional but `.env` values not loaded. 

I'm using the latest version and `.env` is provisioned with all goodies. 

The UI informs the user to provide the STRIPE Secrets. 

Please check. ty! 

```env

DEBUG=True

# Flask SECRET_KEY
SECRET_KEY=Super__hgd

# Stripe Secrets
STRIPE_PUBLISHABLE_KEY=pk_test_WHATEVER
STRIPE_SECRET_KEY=sk_test_WHATEVER

# Server Address (used by Stripe callback)
# Should be the URL used to start the APP
SERVER_ADDRESS=http://localhost:5085/

```

**Comment by barreraalexander** [comment]
Alrighty, so the config.py file is fine -- if a environment variable isn't provided in the .env file, config.py will provide defaults. This is okay yes? But your concern is that the docker-compose.yml file isn't loading the .env file, therefore only defaults are being used?  This should now be fixed with the change I made in Dockerfile. On my end, the UI follows the same evolution as the flask app, where clicking on the "Buy Product" button makes a popup occur about the Stripe secrets.

**Comment by app-generator** [comment]
Hello @barreraalexander 

The test was made with the manual set up. 
If the stripe secrets are provided in `.env` the pop-up is still there and the user is informed to update the configuration. 

I did not debug the app to detect where is the problem.

Please check. Ty!

**Comment by barreraalexander** [comment]
Oof, I got tied up by misnaming a variable. This is fixed.

**Comment by app-generator** [comment]
Validated. Closing! 

Ty @barreraalexander
